baseURL: https://eco.kde.org/
canonifyURLs: true
defaultContentLanguage: en
enableGitInfo: true
enableRobotsTXT: true
i18n:
  content:
    default:
      files:
      - content/_index.md
      - content/BE4FOSS/*.md
      - content/FEEP/*.md
  genToOtherDir: true
  others:
  - title
  - menu
  - strings
languages:
#  de:
#    contentDir: content-trans/de
#    languageCode: de
#    languageName: Deutsch
#    menu:
#      main:
#      - name: Spenden
#        url: https://kde.org/donate
#        weight: 5
#    title: KDE Eco
#    weight: 2
  en:
    languageCode: en
    languageName: English
    menu:
      main:
        - identifier: feep
          name: FEEP
          weight: 2
          url: /feep/energy_efficiency/
        - identifier: be4foss
          name: BE4FOSS
          url: /be4foss/eco-label/
          weight: 3
        - name: Donate
          url: https://kde.org/community/donations/
          weight: 5
    title: KDE Eco
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
module:
  imports:
  - path: invent.kde.org/websites/aether-sass
outputs:
  home:
  - HTML
  - RSS
  section:
  - HTML
params:
  images:
  - /logo-150x150.png
  logo: /logo-150x150.png
  madeByKDE: true
  repoName: eco-kde-org
  showPatrons: false
rssLimit: 4
summaryLength: 30
